### ISSUE TITLE
Recommendation for Inclusion in the Related Works Table

### ISSUE THREAD

**Issue by superkevingit** [lishenghui/awesome-fm-fl#1]
Dear Contributors,

Great job on the survey paper, and thank you for providing a summary page of all related works for the community. We would like to recommend our work on the LoRA-based federated foundation fine-tuning method. Specifically, we revisit FedRA (Su et al., ECCV 2024) with a focus on more realistic GPU memory consumption and propose a knapsack optimization problem to select trainable LoRA layers for each client, considering various memory constraints.

We would greatly appreciate it if you could include our work in the table during your next update to the page.

Thank you!
Zikai Zhang

Link to ArXiv Paper:
https://arxiv.org/abs/2410.10200

Citation Format:
@article{zhang2024fed,
  title={Fed-piLot: Optimizing LoRA Assignment for Efficient Federated Foundation Model Fine-Tuning},
  author={Zhang, Zikai and Xu, Jiahao and Liu, Ping and Hu, Rui},
  journal={arXiv preprint arXiv:2410.10200},
  year={2024}
}

**Comment by lishenghui** [comment]
Hi, 

Thanks for your recommendation. The work is impressive. I have now included it in the table. Please also consider citing our survey in your publication if you think it is relevant.

Best regards,
Shenghui
